### PR TITLE
Support SSL

### PR DESCRIPTION
**Pull request by ebfbedros**
### Description:

Added the following optional parameters to support SSL:
--target-db-enable-ssl=
--target-db-ssl-ca=
--target-db-ssl-no-verify=

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — APPROVED** [review]
@ebfbedros Thank you for taking the time to make this PR. The changes look good and they worked when I tested them.

The only suggestion that I'd have is to maybe switch the two boolean options to be no value options using `addNoValueOption` instead of `addOptionalValueOption`. What you have works though and there's no need to change if you prefer not to.

Any concerns @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
> @ebfbedros Thank you for taking the time to make this PR. The changes look good and they worked when I tested them.
> 
> The only suggestion that I'd have is to maybe switch the two boolean options to be no value options using `addNoValueOption` instead of `addOptionalValueOption`. What you have works though and there's no need to change if you prefer not to.
> 
> Any concerns @AltamashShaikh ?

@snake14 No concerns from my side

**Comment by ebfbedros** [comment]
> @snake14

Thank you for your feedback. I have added your suggestions.

**Comment by snake14** [comment]
Thank you @ebfbedros for making those changes and thank you again for taking the time to create this PR :+1:

**Pull request merged**
